name: release
on:
  release:
    types:
      - published

jobs:
  test:
    name: run tests then publishes release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: yarn test --ci
      - name: install
        run: yarn
      - name: publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
