name: test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test --ci
